import { Flex, Heading } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex minH={"100vh"} justifyContent="center" alignItems="center" as="main">
        <Heading>DEV JOBS!!!!</Heading>
      </Flex>
    </div>
  );
};

export default Home;
